name: Saving Issue
description: Report an issue Saving
labels: ["Saving"]
body:
  - type: markdown
    attributes:
      value: |
        Woops, sorry there was an issue Saving.  Please add any detail you can to this report and check back soon!
  - type: textarea
    id: error-code
    attributes:
      label: Error Code
      render: shell
  - type: textarea
    id: user-description
    attributes:
      label: "Your description of what happened:"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Danke für die Meldung.
